### ISSUE TITLE
Site is offline

### ISSUE THREAD

**Issue by tiramon** [Orabig/CGPuzzleStats#2]
Is there a special reason the site is offline?

**Comment by Orabig** [comment]
There was none.... But it's fixed now.
Thanks for noticing...

**Comment by Orabig** [comment]
Really, you have this message again ?
Can you give me the exact url ?. It seems to be working ok right now for
me... :/

2018-04-12 7:24 GMT+02:00 tiramon <notifications@github.com>:

**Comment by Orabig** [comment]
Ok, I understand. You must have a url with pseudo IDs in it. You should go
back to https://cgstats.crocoware.com/ then click on "Add Pseudo" again.
The application has been reset, and thus have lost all informations about
the pseudos, and have no way (unfortunately) to retrieve some information
from the IDs again. I'm sorry for that.

2018-04-12 7:24 GMT+02:00 tiramon <notifications@github.com>:
